server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8899
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    prefix:
    suffix: .ftl
    template-loader-path: classpath:/templates/
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: pro
    include: qiniu
  http:
    multipart:
      max-file-size: 500Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: config/ehcache.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.xstz.**.domain
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
# 七牛云配置
# bucket是创建的存储空间名
# path对应存储空间的访问域名
qiniu:
  accessKey: h7DrTbpCVd0RZbZzxwTSu9L_ckYWO29U4rl1xqwA
  secretKey: 7GDHZXb9WLD1WY84BOxvSfBJO3V1hGQSS6H0wik3
  bucket: xstz
  path: pcrcxnua8.bkt.clouddn.com
 #ueditor的config.json配置
